Plumbing-Inventory-main/PlumbingInventory/Controllers/ItemCatsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PlumbingInventory.Models;

namespace PlumbingInventory.Controllers
{
    public class ItemCatsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: ItemCats
        public ActionResult Index()
        {
            return View(db.ItemCats.ToList());
        }

        // GET: ItemCats/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ItemCat itemCat = db.ItemCats.Find(id);
            if (itemCat == null)
            {
                return HttpNotFound();
            }
            return View(itemCat);
        }

        // GET: ItemCats/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ItemCats/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ItemCat_ID,ItemCat_Name")] ItemCat itemCat)
        {
            if (ModelState.IsValid)
            {
                
                db.ItemCats.Add(itemCat);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(itemCat);
        }

        // GET: ItemCats/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ItemCat itemCat = db.ItemCats.Find(id);
            if (itemCat == null)
            {
                return HttpNotFound();
            }
            return View(itemCat);
        }

        // POST: ItemCats/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ItemCat_ID,ItemCat_Name")] ItemCat itemCat)
        {
            if (ModelState.IsValid)
            {
                db.Entry(itemCat).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(itemCat);
        }

        // GET: ItemCats/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ItemCat itemCat = db.ItemCats.Find(id);
            if (itemCat == null)
            {
                return HttpNotFound();
            }
            return View(itemCat);
        }

        // POST: ItemCats/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ItemCat itemCat = db.ItemCats.Find(id);
            db.ItemCats.Remove(itemCat);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Plumbing-Inventory-main/PlumbingInventory/Controllers/JobsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PlumbingInventory.Models;

namespace PlumbingInventory.Controllers
{
    public class JobsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Jobs
        public ActionResult Index(Job job, string search)
        {


            List<SelectListItem> list2 = new List<SelectListItem>();

            list2.Add(new SelectListItem()
            {
                Text = "Any",
                Value = "Any"
            });

            list2.Add(new SelectListItem()
            {
                Text = "Complete",
                Value = "Complete"
            });

            list2.Add(new SelectListItem()
            {
                Text = "Incomplete",
                Value = "Incomplete"
            });







            ViewBag.Job_Status = list2;


            if (job.Job_Status == "Complete")
            {
                //Index action method will return a view with a student records based on what a user specify the value in textbox  
                return View(db.Jobs.Where(x => x.Job_Name.Contains(search) && x.Job_Status == "Complete" || search == null).ToList());
            }

            else if (job.Job_Status == "Incomplete")
            {
                //Index action method will return a view with a student records based on what a user specify the value in textbox  
                return View(db.Jobs.Where(x => x.Job_Name.Contains(search) && x.Job_Status == "Incomplete" || search == null).ToList());
            }
            else if (job.Job_Status == "Any")
            {

                return View(db.Jobs.Where(x => x.Job_Name.Contains(search) || search == null).ToList());
            }


            return View(db.Jobs.ToList());

        }



        // GET: Jobs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Job job = db.Jobs.Find(id);
            if (job == null)
            {
                return HttpNotFound();
            }
            return View(job);
        }



        public ActionResult JobInfo(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Job job = db.Jobs.Find(id);
            if (job == null)
            {
                return HttpNotFound();
            }

            JobVM jvm = new JobVM();

            jvm.Job_IDs = job.Job_ID;
            jvm.Job_Names = job.Job_Name;
            jvm.Job_Dates = job.Job_Date;
            jvm.Job_Statuss = job.Job_Status;

            jvm.ItemRecords = (from l in db.ItemRecords where l.Job_ID == job.Job_ID select l).ToList();

            return View(jvm);
        }

        public ActionResult UpdateStatus(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Job job = db.Jobs.Find(id);
            if (job == null)
            {
                return HttpNotFound();
            }
            if(job.Job_Status == "Incomplete")
            {

                job.Job_Status = "Complete";

            }
            else if(job.Job_Status == "Complete")
            {

                job.Job_Status = "Incomplete";

            }
            else
            {

                job.Job_Status = "Complete";
            }
            db.Entry(job).State = EntityState.Modified;
            db.SaveChanges();
            
            return RedirectToAction("JobInfo", new { id = job.Job_ID });
        }







        // GET: Jobs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Jobs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Job_ID,Job_Name,Job_Date")] Job job)
        {
            if (ModelState.IsValid)
            {
                job.Job_Status = "Incomplete";
                db.Jobs.Add(job);
                db.SaveChanges();
                return RedirectToAction("JobInfo", new { id = job.Job_ID });
            }

            return View(job);
        }


        //public ActionResult JobDetails(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Job job = db.Jobs.Find(id);
        //    if (job == null)
        //    {
        //        return HttpNotFound();
        //    }

        //    var vm = new JobVM();
        //    vm.Job_ID = job.Job_ID;

        //    vm.Job_Name = job.Job_Name;

        //    vm.Job_Date = job.Job_Date;

        //    vm.RecordData = (from d in db.ItemRecords where d.Job_ID == id select d).ToList();

        //    vm.ItemData = (db.Items).ToList();

        //    return View(vm);
        //}

        public ActionResult AddToCart(int? id)
        {
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
           
            else
            {

                var item = db.Items.Find(id);

                item.Item_Qty = 30;


                db.Entry(item).State = EntityState.Modified;
                db.SaveChanges();

            }
            if (Session["cart"] == null)
            {
                List<ItemRecord> cart = new List<ItemRecord>();
                var product = db.Items.Find(id);
                cart.Add(new ItemRecord()
                {
                    ItemRecord_Status = "Incomplete",
                    Item_ID = (int)id
                });
                Session["cart"] = cart;
            }
            else
            {
                List<ItemRecord> cart = (List<ItemRecord>)Session["cart"];
                var product = db.Items.Find(id);
                cart.Add(new ItemRecord()
                {
                    ItemRecord_Status = "Incomplete",
                    Item_ID = (int)id
                });
                Session["cart"] = cart;
            }
            return Redirect("JobDetails");
        }



        //[HttpPost]
        //public ActionResult JobDetails(Item item)
        //{

        //    ItemRecord ir = new ItemRecord();


        //    ir.Item_ID = item.Item_ID;
        //    ir.ItemRecord_QtyUsed = item.Item_Qty;
        //    ir.ItemRecord_Status = "Incomplete";

        //    db.ItemRecords.Add(ir);
        //    db.SaveChanges();


        //    return View();
        //}



        // GET: Jobs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Job job = db.Jobs.Find(id);
            if (job == null)
            {
                return HttpNotFound();
            }
            return View(job);
        }

        // POST: Jobs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Job_ID,Job_Name,Job_Date")] Job job)
        {
            if (ModelState.IsValid)
            {
                db.Entry(job).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(job);
        }

        // GET: Jobs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Job job = db.Jobs.Find(id);
            if (job == null)
            {
                return HttpNotFound();
            }
            return View(job);
        }

        // POST: Jobs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Job job = db.Jobs.Find(id);
            db.Jobs.Remove(job);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Plumbing-Inventory-main/PlumbingInventory/Views/Shared/_Layout.cshtml
<!DOCTYPE html>


<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <style>

        body {
            padding-top: 0px;
        }
    </style>


    <script src="https://bootswatch.com/_vendor/jquery/dist/jquery.min.js"></script>
    <script src="https://bootswatch.com/_vendor/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">Plumbing Inventory</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarColor02">
            <ul class="navbar-nav mr-auto">

                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index", "Jobs")">Jobs</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index", "Items")">Inventory</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("CatalogList", "Items")">Item Catalog</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index", "ItemCats")">Item Categories</a>
                </li>

            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </nav>
    <br />

    @*<div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    </ul>
                    @Html.Partial("_LoginPartial")
                </div>
            </div>
        </div>*@




    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; Plumbing Inventory System ~ By Radical Solutions</p>
        </footer>
    </div>


  
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>